### PR TITLE
Screen reader improvements - focus management and content

### PR DESCRIPTION
**Pull request by mcheung-nhs**
Improved focus when moving between 'screens' so screen readers get feedback and read the appropriate message. Also improved feedback to screen readers on the initial page - described that there are 2 buttons, and better description of the buttons.

### CODE REVIEW

**Comment by the-nathan-smith** [comment]
All looks good to me.

**Comment by mikemonteith** [comment]
This PR adds a new requirement for implementors - they need to include some CSS where it was purely JS before.
Wondering if we could inject the CSS with javascript in a `<style>` tag instead of introducing another installation step 🤔

**Comment by mcheung-nhs** [comment]
@mikemonteith - yes unfortunately there is another step to include CSS. Regarding inline styling, this is something we try to avoid because if anyone has their own CSS override stylings, then this would interfere with them.

**Comment by mikemonteith** [comment]
@mcheung-nhs I've added a CSS loader into the webpack config so the CSS is injected into `<style>` inside the HTML head.
I'm happy with your changes - if you're happy with my addition you can feel free to merge it

**Review by mikemonteith — APPROVED** [review]

**Comment by mcheung-nhs** [comment]
@mikemonteith - all looks good so happy to merge. Will you be doing a release soon?

**Pull request merged**
