### PR TITLE
Send blank messages

### PR DESCRIPTION
**Pull request by the-nathan-smith**
Removed the if statement which checks if the message box is empty or not so that blank messages can be sent to the database as well.

### CODE REVIEW

**Comment by mikemonteith** [comment]
Have you tested that the backend actually accepts and stores the blank message?

**Comment by mikemonteith** [comment]
There's a failing unit test here https://github.com/nhsuk/user-feedback-form/blob/master/tests/integration/text-comments.test.js#L47

**Comment by prembonsall** [comment]
Screenshot 2020-05-13 at 11 16 16

Db accepts and stores empty comments

**Comment by mikemonteith** [comment]
related to https://github.com/nhsuk/user-feedback-store/issues/6

**Comment by the-nathan-smith** [comment]
Change request "Need to fix the failing test" completed. 
https://github.com/nhsuk/user-feedback-form/pull/22/commits/6b3298853b05c37b49d50c64e7d3c62446572329

**Pull request merged**
